name: 'Sonar'
on:
  workflow_run:
    workflows: [ 'Android Build' ]
    types:
      - completed
      
jobs:
  sonar:
    name: 'Sonar analysis'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-src/KV4PHT
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read # Required to download artifacts

